### ISSUE TITLE
Design roadmap using MDX with Next.js

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#107]
There is a standard [markdown roadmap](https://regels.overheid.nl/roadmap) deployed using the strapi cms backend.

Please investigate:
- [ ] What design options are there to present that roadmap using MDX?
- [ ] Illustrate using the [MDX test page](https://regels.overheid.nl/mdx-test)
- [ ] Take the *Rijkshuisstijl* into account.
- [ ] Document CI/CD for local development as requested in #93
