### ISSUE TITLE
Facilitate self-hosted Solid Pod infrastructure for demo purpose(s)

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#154]
Solid is a [specification](https://solidproject.org/TR/protocol) that lets people store their data securely in decentralized data stores called Pods. Pods are like secure personal web servers for data. When data is stored in someone's Pod, they control which people and applications can access it.

A Solid server allows you to register for a Pod and a WebID.
We can either [use a publicly available server](https://solidproject.org/users/get-a-pod) or follow the steps on this page to set up your own.

# To do
- [x] select an open-source Solid server (see [options available](https://solidproject.org//self-hosting/css))
- [x] install Solid server
- [x] provide **3** pods / webids to fill the example citizens: **Sharon**, **Inge** and **Tom**
- [x] provide **1** pod / webid to function as municipality inbox: **Utrecht**

Installation done. To do's left:

- [x] MinBZK/regels.overheid.nl#156 
- [x] MinBZK/regels.overheid.nl#157 
- [x] MinBZK/regels.overheid.nl#158 

Left Node Solid Server approach:
- [x] MinBZK/regels.overheid.nl#159 
- [ ] MinBZK/regels.overheid.nl#160

**Comment by sgort** [comment]
Related to #89

**Comment by sgort** [comment]
Ga poging doen multi-user server variant te installeren waarmee nieuwe gebruikers zich kunnen aanmelden en zodoende een WebID `gebruikersnaam.mijnsolidpod.nl` krijgen.

**Comment by sgort** [comment]
Installation done. To do's left:

- [ ] wildcard certificate
- [ ] email service
- [ ] systemctl service

**Comment by hayoschreijer** [comment]
@sgort Laat even weten als je ondersteuning bij de Solid installatie nodig hebt; onze Joep heeft dit een paar keer eerder gedaan en geconfigureerd.

**Comment by sgort** [comment]
Super @hayoschreijer , ik kan wel wat hulp gebruiken met goed config van de wildcard certificaat die ik voor `*.mijnsolidpod.nl` in de Node Solid Server heb geconfigureerd. Dat gaat nl. nog niet goed. Na registratie krijg ik een SSL errror ivm ontbreken certificaat. Zie #156

**Comment by hayoschreijer** [comment]
Steven, ik kreeg snel reactie. Joep was niet enthousiast: quote Joep: "Oh
god, de Node versie van Solid... Die is al lang verlaten door het hele
team, en was vanaf het begin al een no-go voor veel mensen. Als het inhoudt
om daar ondersteuning op te leveren, dan zeg ik nee. Ik help graag als ze
serieus zijn over pods, maar support op de NSS ga ik niet doen. Dat is
alsof je met een rol ducttape een zinkende titanic drijvend probeert te
houden. "

Even afstemmen? De genuanceerde mededeling is dat we Solid afraden iig, al
helemaal de node server. De CSS is een betere optie, maar fixt niet de
fundamentele issues met RDF en complexiteit van Solid. Er zijn betere
implementaties die compatible blijven met SOlid-specs aan de buitenzijde,
maar die wel beheerbaar zijn.


Met vriendelijke groeten,

Hayo Schreijer
managing director Dexes
T: 06-4637 4892
E: ***@***.***


Op do 2 feb. 2023 om 17:02 schreef Datafluisteraar ***@***.***

**Comment by sgort** [comment]
Haha. Heerlijke quote. Appreciated! Serieus. 

Switchen naar CSS lijkt me prima. Dat pak ik op. 

PS
Ben sowieso benieuwd naar analyse en die betere implementaties.

**Comment by sgort** [comment]
Created pod's for

- https://mijnsolidpod.nl/sharon/profile/card#me
- https://mijnsolidpod.nl/inge/profile/card#me
- https://mijnsolidpod.nl/tom/profile/card#me

**Comment by sgort** [comment]
Will leave `subdomain` [config](https://github.com/sgort/css-mashlib/tree/mijnsolidpod/subdomain-config) for now. Will try again after VIL demo.

**Comment by sgort** [comment]
Can be closed. Not in scope anymore.
