### ISSUE TITLE
Specify DevOps requirements for consultancy

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#90]
> For regels.overheid.nl, we work with work packages, these are small jobs for a fixed fee to deliver part functionality (proof of concept), including minimal documentation and tests.

There is a need for expert advice and/or audit for the CI/CD pipeline ánd quality of service of the intended multi-stack environment.

## Tasks
- [x] specify the need
- [ ] peer review
- [ ] request consultation in a work package

**Comment by onursagir** [comment]
Requirements:
- Achieving a 100% score on https://internet.nl/site/regels.overheid.nl/1809048
- Creating Github Actions
- Optimising the development environment with docker compose
- Dockerizing the applications and setting up a production environment

**Comment by sgort** [comment]
## Story points

The initial estimate of the size of this work package is:
- [ ] 20 (ie €1000,=)
- [x] 40 (ie €2000,=)
- [ ] 100 (ie €5000,=)

## Definition of “done”

- [ ] Relevant documentation has been created and made available
- [ ] Approved by Product Owner
- [ ] Code has undergone a peer review

**Comment by Burrowfield** [comment]
Dag Steven, Daniel Langeveld hier.
Idan en ik pakken deze graag voor je op, op persoonlijke titel (freelance).

Idan zijn Github: github.com/idane

Communicatie mag via mij (assignen mag ook aan mij/hem). 

Idan doet al ruim 10 jaar als full-stack developer en Dev-Ops expert werk voor overheid en commerciële partijen. Ook is hij zeer ervaren met Docker en CI/CD & Devops.

Mij ken je als de communicatie-genie en gezellige gesprekpartner die ik ben. Ik ben er vooral om jullie met elkaar te verbinden.

@onursagir Ik begrijp dat ik even met jou kan afstemmen, je kan me vinden op Slack onder 'Daniel Langeveld' of alternatief even aan Steven mijn nummer vragen!

**Comment by sgort** [comment]
Inschrijving gesloten as we speak. Will be assigned aan [Idan](https://github.com/idan279).

**Comment by sgort** [comment]
@idan279 laat even weten op welke manier @onursagir jou kan contacten voor nadere afstemming.
Mijn tel nr is 06 52 48 69 51. Je kan jezelf ook onboarden op het #regels.overheid.nl [Slack kanaal van Code for NL](https://praatmee.codefor.nl/).

**Comment by onursagir** [comment]
@idan279 mij kan je contacten via mehmet@gngn.nl

**Comment by sgort** [comment]
Nice to have:
- [ ] release CI/CD pipeline with semantic versioning connected to github's pull-requests

**Comment by sgort** [comment]
Please consider #10 as a first priority.
